import Head from "next/head";
import Sidebar from "../components/Sidebar/Sidebar";
import { Badge, Box, Flex, Link, Text } from "@chakra-ui/react";

const Home = () => {
  return (
    <Box as="section" bg="gray.50" minH="100vh">
      <Head>
        <title>Mapsa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <Box ml={60} minH="100vh">
        <Box as="main" p="4">
          <Flex
            justify="end"
            align="end"
            p={4}
            borderWidth="4px"
            borderStyle="dashed"
            rounded="md"
            h="96"
          >
            <Text fontSize="md">
              created by
              <Badge colorScheme="green">
                <Link href="https://github.com/Ehsan-Yari-React/" isExternal>
                  ehsan yari
                </Link>
              </Badge>
            </Text>
          </Flex>
        </Box>
      </Box>
    </Box>
  );
};
export default Home;
